[Log]
	Environment = "development" # "production" or "development"
	Level = "info"
	Outputs = ["stderr"]
[DB]
	Name = "sync"
	User = "test_user"
	Password = "test_password"
	Host = "localhost"
	Port = "5436"
	MaxConns = 10
[Synchronizer]
	SyncInterval = "10s"
	SyncChunkSize = 1000
	# 0 means find out the block of ETROG upgrade
	GenesisBlockNumber = 0
[Etherman]
	L1URL = "http://your.L1node.url"
	[Etherman.Contracts]
		GlobalExitRootManagerAddr = "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"
		RollupManagerAddr = "0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2"
		ZkEVMAddr = "0x519E42c24163192Dca44CD3fBDCEBF6be9130987"
	