// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import mock "github.com/stretchr/testify/mock"

// EthermanInterface is an autogenerated mock type for the EthermanInterface type
type EthermanInterface struct {
	mock.Mock
}

type EthermanInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *EthermanInterface) EXPECT() *EthermanInterface_Expecter {
	return &EthermanInterface_Expecter{mock: &_m.Mock}
}

// NewEthermanInterface creates a new instance of EthermanInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthermanInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthermanInterface {
	mock := &EthermanInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
