// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	actions "github.com/0xPolygonHermez/zkevm-synchronizer-l1/synchronizer/actions"

	entities "github.com/0xPolygonHermez/zkevm-synchronizer-l1/state/entities"

	etherman "github.com/0xPolygonHermez/zkevm-synchronizer-l1/etherman"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PreviousProcessor is an autogenerated mock type for the PreviousProcessor type
type PreviousProcessor struct {
	mock.Mock
}

type PreviousProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *PreviousProcessor) EXPECT() *PreviousProcessor_Expecter {
	return &PreviousProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, forkId, order, l1Block, dbTx
func (_m *PreviousProcessor) Process(ctx context.Context, forkId actions.ForkIdType, order etherman.Order, l1Block *etherman.Block, dbTx entities.Tx) error {
	ret := _m.Called(ctx, forkId, order, l1Block, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, actions.ForkIdType, etherman.Order, *etherman.Block, entities.Tx) error); ok {
		r0 = rf(ctx, forkId, order, l1Block, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreviousProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type PreviousProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - forkId actions.ForkIdType
//   - order etherman.Order
//   - l1Block *etherman.Block
//   - dbTx entities.Tx
func (_e *PreviousProcessor_Expecter) Process(ctx interface{}, forkId interface{}, order interface{}, l1Block interface{}, dbTx interface{}) *PreviousProcessor_Process_Call {
	return &PreviousProcessor_Process_Call{Call: _e.mock.On("Process", ctx, forkId, order, l1Block, dbTx)}
}

func (_c *PreviousProcessor_Process_Call) Run(run func(ctx context.Context, forkId actions.ForkIdType, order etherman.Order, l1Block *etherman.Block, dbTx entities.Tx)) *PreviousProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(actions.ForkIdType), args[2].(etherman.Order), args[3].(*etherman.Block), args[4].(entities.Tx))
	})
	return _c
}

func (_c *PreviousProcessor_Process_Call) Return(_a0 error) *PreviousProcessor_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreviousProcessor_Process_Call) RunAndReturn(run func(context.Context, actions.ForkIdType, etherman.Order, *etherman.Block, entities.Tx) error) *PreviousProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessSequenceBatches provides a mock function with given fields: ctx, forkId, sequencedBatches, blockNumber, l1BlockTimestamp, dbTx
func (_m *PreviousProcessor) ProcessSequenceBatches(ctx context.Context, forkId actions.ForkIdType, sequencedBatches []etherman.SequencedBatch, blockNumber uint64, l1BlockTimestamp time.Time, dbTx entities.Tx) error {
	ret := _m.Called(ctx, forkId, sequencedBatches, blockNumber, l1BlockTimestamp, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessSequenceBatches")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, actions.ForkIdType, []etherman.SequencedBatch, uint64, time.Time, entities.Tx) error); ok {
		r0 = rf(ctx, forkId, sequencedBatches, blockNumber, l1BlockTimestamp, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreviousProcessor_ProcessSequenceBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessSequenceBatches'
type PreviousProcessor_ProcessSequenceBatches_Call struct {
	*mock.Call
}

// ProcessSequenceBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - forkId actions.ForkIdType
//   - sequencedBatches []etherman.SequencedBatch
//   - blockNumber uint64
//   - l1BlockTimestamp time.Time
//   - dbTx entities.Tx
func (_e *PreviousProcessor_Expecter) ProcessSequenceBatches(ctx interface{}, forkId interface{}, sequencedBatches interface{}, blockNumber interface{}, l1BlockTimestamp interface{}, dbTx interface{}) *PreviousProcessor_ProcessSequenceBatches_Call {
	return &PreviousProcessor_ProcessSequenceBatches_Call{Call: _e.mock.On("ProcessSequenceBatches", ctx, forkId, sequencedBatches, blockNumber, l1BlockTimestamp, dbTx)}
}

func (_c *PreviousProcessor_ProcessSequenceBatches_Call) Run(run func(ctx context.Context, forkId actions.ForkIdType, sequencedBatches []etherman.SequencedBatch, blockNumber uint64, l1BlockTimestamp time.Time, dbTx entities.Tx)) *PreviousProcessor_ProcessSequenceBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(actions.ForkIdType), args[2].([]etherman.SequencedBatch), args[3].(uint64), args[4].(time.Time), args[5].(entities.Tx))
	})
	return _c
}

func (_c *PreviousProcessor_ProcessSequenceBatches_Call) Return(_a0 error) *PreviousProcessor_ProcessSequenceBatches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreviousProcessor_ProcessSequenceBatches_Call) RunAndReturn(run func(context.Context, actions.ForkIdType, []etherman.SequencedBatch, uint64, time.Time, entities.Tx) error) *PreviousProcessor_ProcessSequenceBatches_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreviousProcessor creates a new instance of PreviousProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreviousProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreviousProcessor {
	mock := &PreviousProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
