// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	entities "github.com/0xPolygonHermez/zkevm-synchronizer-l1/state/entities"

	mock "github.com/stretchr/testify/mock"
)

// stateL1SeqInterface is an autogenerated mock type for the stateL1SeqInterface type
type stateL1SeqInterface struct {
	mock.Mock
}

type stateL1SeqInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *stateL1SeqInterface) EXPECT() *stateL1SeqInterface_Expecter {
	return &stateL1SeqInterface_Expecter{mock: &_m.Mock}
}

// BeginStateTransaction provides a mock function with given fields: ctx
func (_m *stateL1SeqInterface) BeginStateTransaction(ctx context.Context) (entities.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginStateTransaction")
	}

	var r0 entities.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (entities.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) entities.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// stateL1SeqInterface_BeginStateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginStateTransaction'
type stateL1SeqInterface_BeginStateTransaction_Call struct {
	*mock.Call
}

// BeginStateTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *stateL1SeqInterface_Expecter) BeginStateTransaction(ctx interface{}) *stateL1SeqInterface_BeginStateTransaction_Call {
	return &stateL1SeqInterface_BeginStateTransaction_Call{Call: _e.mock.On("BeginStateTransaction", ctx)}
}

func (_c *stateL1SeqInterface_BeginStateTransaction_Call) Run(run func(ctx context.Context)) *stateL1SeqInterface_BeginStateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *stateL1SeqInterface_BeginStateTransaction_Call) Return(_a0 entities.Tx, _a1 error) *stateL1SeqInterface_BeginStateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *stateL1SeqInterface_BeginStateTransaction_Call) RunAndReturn(run func(context.Context) (entities.Tx, error)) *stateL1SeqInterface_BeginStateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreviousBlock provides a mock function with given fields: ctx, depth, tx
func (_m *stateL1SeqInterface) GetPreviousBlock(ctx context.Context, depth uint64, tx entities.Tx) (*entities.L1Block, error) {
	ret := _m.Called(ctx, depth, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousBlock")
	}

	var r0 *entities.L1Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, entities.Tx) (*entities.L1Block, error)); ok {
		return rf(ctx, depth, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, entities.Tx) *entities.L1Block); ok {
		r0 = rf(ctx, depth, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.L1Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, entities.Tx) error); ok {
		r1 = rf(ctx, depth, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// stateL1SeqInterface_GetPreviousBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreviousBlock'
type stateL1SeqInterface_GetPreviousBlock_Call struct {
	*mock.Call
}

// GetPreviousBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - depth uint64
//   - tx entities.Tx
func (_e *stateL1SeqInterface_Expecter) GetPreviousBlock(ctx interface{}, depth interface{}, tx interface{}) *stateL1SeqInterface_GetPreviousBlock_Call {
	return &stateL1SeqInterface_GetPreviousBlock_Call{Call: _e.mock.On("GetPreviousBlock", ctx, depth, tx)}
}

func (_c *stateL1SeqInterface_GetPreviousBlock_Call) Run(run func(ctx context.Context, depth uint64, tx entities.Tx)) *stateL1SeqInterface_GetPreviousBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(entities.Tx))
	})
	return _c
}

func (_c *stateL1SeqInterface_GetPreviousBlock_Call) Return(_a0 *entities.L1Block, _a1 error) *stateL1SeqInterface_GetPreviousBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *stateL1SeqInterface_GetPreviousBlock_Call) RunAndReturn(run func(context.Context, uint64, entities.Tx) (*entities.L1Block, error)) *stateL1SeqInterface_GetPreviousBlock_Call {
	_c.Call.Return(run)
	return _c
}

// newStateL1SeqInterface creates a new instance of stateL1SeqInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStateL1SeqInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *stateL1SeqInterface {
	mock := &stateL1SeqInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
