// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgstorage "github.com/0xPolygonHermez/zkevm-synchronizer-l1/db/pgstorage"

	pgx "github.com/jackc/pgx/v4"
)

// stateProcessSequenceBatches is an autogenerated mock type for the stateProcessSequenceBatches type
type stateProcessSequenceBatches struct {
	mock.Mock
}

type stateProcessSequenceBatches_Expecter struct {
	mock *mock.Mock
}

func (_m *stateProcessSequenceBatches) EXPECT() *stateProcessSequenceBatches_Expecter {
	return &stateProcessSequenceBatches_Expecter{mock: &_m.Mock}
}

// AddSequencedBatches provides a mock function with given fields: ctx, sequence, dbTx
func (_m *stateProcessSequenceBatches) AddSequencedBatches(ctx context.Context, sequence pgstorage.SequencedBatches, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, sequence, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddSequencedBatches")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgstorage.SequencedBatches, pgx.Tx) error); ok {
		r0 = rf(ctx, sequence, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// stateProcessSequenceBatches_AddSequencedBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSequencedBatches'
type stateProcessSequenceBatches_AddSequencedBatches_Call struct {
	*mock.Call
}

// AddSequencedBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - sequence pgstorage.SequencedBatches
//   - dbTx pgx.Tx
func (_e *stateProcessSequenceBatches_Expecter) AddSequencedBatches(ctx interface{}, sequence interface{}, dbTx interface{}) *stateProcessSequenceBatches_AddSequencedBatches_Call {
	return &stateProcessSequenceBatches_AddSequencedBatches_Call{Call: _e.mock.On("AddSequencedBatches", ctx, sequence, dbTx)}
}

func (_c *stateProcessSequenceBatches_AddSequencedBatches_Call) Run(run func(ctx context.Context, sequence pgstorage.SequencedBatches, dbTx pgx.Tx)) *stateProcessSequenceBatches_AddSequencedBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgstorage.SequencedBatches), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *stateProcessSequenceBatches_AddSequencedBatches_Call) Return(_a0 error) *stateProcessSequenceBatches_AddSequencedBatches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *stateProcessSequenceBatches_AddSequencedBatches_Call) RunAndReturn(run func(context.Context, pgstorage.SequencedBatches, pgx.Tx) error) *stateProcessSequenceBatches_AddSequencedBatches_Call {
	_c.Call.Return(run)
	return _c
}

// newStateProcessSequenceBatches creates a new instance of stateProcessSequenceBatches. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStateProcessSequenceBatches(t interface {
	mock.TestingT
	Cleanup(func())
}) *stateProcessSequenceBatches {
	mock := &stateProcessSequenceBatches{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
