// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	entities "github.com/0xPolygonHermez/zkevm-synchronizer-l1/state/entities"
	mock "github.com/stretchr/testify/mock"
)

// StateStorageCompatibilityCheckerInterface is an autogenerated mock type for the StateStorageCompatibilityCheckerInterface type
type StateStorageCompatibilityCheckerInterface struct {
	mock.Mock
}

type StateStorageCompatibilityCheckerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StateStorageCompatibilityCheckerInterface) EXPECT() *StateStorageCompatibilityCheckerInterface_Expecter {
	return &StateStorageCompatibilityCheckerInterface_Expecter{mock: &_m.Mock}
}

// CheckAndUpdateStorage provides a mock function with given fields: ctx, runBoundData, overrideStorageCheck, dbTx
func (_m *StateStorageCompatibilityCheckerInterface) CheckAndUpdateStorage(ctx context.Context, runBoundData entities.StorageContentsBoundData, overrideStorageCheck bool, dbTx entities.Tx) error {
	ret := _m.Called(ctx, runBoundData, overrideStorageCheck, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndUpdateStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.StorageContentsBoundData, bool, entities.Tx) error); ok {
		r0 = rf(ctx, runBoundData, overrideStorageCheck, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndUpdateStorage'
type StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call struct {
	*mock.Call
}

// CheckAndUpdateStorage is a helper method to define mock.On call
//   - ctx context.Context
//   - runBoundData entities.StorageContentsBoundData
//   - overrideStorageCheck bool
//   - dbTx entities.Tx
func (_e *StateStorageCompatibilityCheckerInterface_Expecter) CheckAndUpdateStorage(ctx interface{}, runBoundData interface{}, overrideStorageCheck interface{}, dbTx interface{}) *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call {
	return &StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call{Call: _e.mock.On("CheckAndUpdateStorage", ctx, runBoundData, overrideStorageCheck, dbTx)}
}

func (_c *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call) Run(run func(ctx context.Context, runBoundData entities.StorageContentsBoundData, overrideStorageCheck bool, dbTx entities.Tx)) *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.StorageContentsBoundData), args[2].(bool), args[3].(entities.Tx))
	})
	return _c
}

func (_c *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call) Return(_a0 error) *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call) RunAndReturn(run func(context.Context, entities.StorageContentsBoundData, bool, entities.Tx) error) *StateStorageCompatibilityCheckerInterface_CheckAndUpdateStorage_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateStorageCompatibilityCheckerInterface creates a new instance of StateStorageCompatibilityCheckerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateStorageCompatibilityCheckerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateStorageCompatibilityCheckerInterface {
	mock := &StateStorageCompatibilityCheckerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
