// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StorageCompatibilityChecker is an autogenerated mock type for the StorageCompatibilityChecker type
type StorageCompatibilityChecker struct {
	mock.Mock
}

type StorageCompatibilityChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageCompatibilityChecker) EXPECT() *StorageCompatibilityChecker_Expecter {
	return &StorageCompatibilityChecker_Expecter{mock: &_m.Mock}
}

// CheckAndUpdateStorage provides a mock function with given fields: ctx
func (_m *StorageCompatibilityChecker) CheckAndUpdateStorage(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndUpdateStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageCompatibilityChecker_CheckAndUpdateStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndUpdateStorage'
type StorageCompatibilityChecker_CheckAndUpdateStorage_Call struct {
	*mock.Call
}

// CheckAndUpdateStorage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageCompatibilityChecker_Expecter) CheckAndUpdateStorage(ctx interface{}) *StorageCompatibilityChecker_CheckAndUpdateStorage_Call {
	return &StorageCompatibilityChecker_CheckAndUpdateStorage_Call{Call: _e.mock.On("CheckAndUpdateStorage", ctx)}
}

func (_c *StorageCompatibilityChecker_CheckAndUpdateStorage_Call) Run(run func(ctx context.Context)) *StorageCompatibilityChecker_CheckAndUpdateStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageCompatibilityChecker_CheckAndUpdateStorage_Call) Return(_a0 error) *StorageCompatibilityChecker_CheckAndUpdateStorage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageCompatibilityChecker_CheckAndUpdateStorage_Call) RunAndReturn(run func(context.Context) error) *StorageCompatibilityChecker_CheckAndUpdateStorage_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageCompatibilityChecker creates a new instance of StorageCompatibilityChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageCompatibilityChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageCompatibilityChecker {
	mock := &StorageCompatibilityChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
