// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	pgx "github.com/jackc/pgx/v4"
	mock "github.com/stretchr/testify/mock"
)

// StorageResetInterface is an autogenerated mock type for the StorageResetInterface type
type StorageResetInterface struct {
	mock.Mock
}

type StorageResetInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageResetInterface) EXPECT() *StorageResetInterface_Expecter {
	return &StorageResetInterface_Expecter{mock: &_m.Mock}
}

// Reset provides a mock function with given fields: ctx, blockNumber, dbTx
func (_m *StorageResetInterface) Reset(ctx context.Context, blockNumber uint64, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, blockNumber, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, pgx.Tx) error); ok {
		r0 = rf(ctx, blockNumber, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageResetInterface_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type StorageResetInterface_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
//   - dbTx pgx.Tx
func (_e *StorageResetInterface_Expecter) Reset(ctx interface{}, blockNumber interface{}, dbTx interface{}) *StorageResetInterface_Reset_Call {
	return &StorageResetInterface_Reset_Call{Call: _e.mock.On("Reset", ctx, blockNumber, dbTx)}
}

func (_c *StorageResetInterface_Reset_Call) Run(run func(ctx context.Context, blockNumber uint64, dbTx pgx.Tx)) *StorageResetInterface_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageResetInterface_Reset_Call) Return(_a0 error) *StorageResetInterface_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageResetInterface_Reset_Call) RunAndReturn(run func(context.Context, uint64, pgx.Tx) error) *StorageResetInterface_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageResetInterface creates a new instance of StorageResetInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageResetInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageResetInterface {
	mock := &StorageResetInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
