// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import (
	context "context"

	pgstorage "github.com/0xPolygonHermez/zkevm-synchronizer-l1/db/pgstorage"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"
)

// StorageBlockInterface is an autogenerated mock type for the StorageBlockInterface type
type StorageBlockInterface struct {
	mock.Mock
}

type StorageBlockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageBlockInterface) EXPECT() *StorageBlockInterface_Expecter {
	return &StorageBlockInterface_Expecter{mock: &_m.Mock}
}

// AddBlock provides a mock function with given fields: ctx, block, dbTx
func (_m *StorageBlockInterface) AddBlock(ctx context.Context, block *pgstorage.L1Block, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, block, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pgstorage.L1Block, pgx.Tx) error); ok {
		r0 = rf(ctx, block, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageBlockInterface_AddBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlock'
type StorageBlockInterface_AddBlock_Call struct {
	*mock.Call
}

// AddBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - block *pgstorage.L1Block
//   - dbTx pgx.Tx
func (_e *StorageBlockInterface_Expecter) AddBlock(ctx interface{}, block interface{}, dbTx interface{}) *StorageBlockInterface_AddBlock_Call {
	return &StorageBlockInterface_AddBlock_Call{Call: _e.mock.On("AddBlock", ctx, block, dbTx)}
}

func (_c *StorageBlockInterface_AddBlock_Call) Run(run func(ctx context.Context, block *pgstorage.L1Block, dbTx pgx.Tx)) *StorageBlockInterface_AddBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgstorage.L1Block), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageBlockInterface_AddBlock_Call) Return(_a0 error) *StorageBlockInterface_AddBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageBlockInterface_AddBlock_Call) RunAndReturn(run func(context.Context, *pgstorage.L1Block, pgx.Tx) error) *StorageBlockInterface_AddBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastBlock provides a mock function with given fields: ctx, dbTx
func (_m *StorageBlockInterface) GetLastBlock(ctx context.Context, dbTx pgx.Tx) (*pgstorage.L1Block, error) {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastBlock")
	}

	var r0 *pgstorage.L1Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) (*pgstorage.L1Block, error)); ok {
		return rf(ctx, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) *pgstorage.L1Block); ok {
		r0 = rf(ctx, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgstorage.L1Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx) error); ok {
		r1 = rf(ctx, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageBlockInterface_GetLastBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastBlock'
type StorageBlockInterface_GetLastBlock_Call struct {
	*mock.Call
}

// GetLastBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx pgx.Tx
func (_e *StorageBlockInterface_Expecter) GetLastBlock(ctx interface{}, dbTx interface{}) *StorageBlockInterface_GetLastBlock_Call {
	return &StorageBlockInterface_GetLastBlock_Call{Call: _e.mock.On("GetLastBlock", ctx, dbTx)}
}

func (_c *StorageBlockInterface_GetLastBlock_Call) Run(run func(ctx context.Context, dbTx pgx.Tx)) *StorageBlockInterface_GetLastBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx))
	})
	return _c
}

func (_c *StorageBlockInterface_GetLastBlock_Call) Return(_a0 *pgstorage.L1Block, _a1 error) *StorageBlockInterface_GetLastBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageBlockInterface_GetLastBlock_Call) RunAndReturn(run func(context.Context, pgx.Tx) (*pgstorage.L1Block, error)) *StorageBlockInterface_GetLastBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreviousBlock provides a mock function with given fields: ctx, offset, dbTx
func (_m *StorageBlockInterface) GetPreviousBlock(ctx context.Context, offset uint64, dbTx pgx.Tx) (*pgstorage.L1Block, error) {
	ret := _m.Called(ctx, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousBlock")
	}

	var r0 *pgstorage.L1Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, pgx.Tx) (*pgstorage.L1Block, error)); ok {
		return rf(ctx, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, pgx.Tx) *pgstorage.L1Block); ok {
		r0 = rf(ctx, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgstorage.L1Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, pgx.Tx) error); ok {
		r1 = rf(ctx, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageBlockInterface_GetPreviousBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreviousBlock'
type StorageBlockInterface_GetPreviousBlock_Call struct {
	*mock.Call
}

// GetPreviousBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - dbTx pgx.Tx
func (_e *StorageBlockInterface_Expecter) GetPreviousBlock(ctx interface{}, offset interface{}, dbTx interface{}) *StorageBlockInterface_GetPreviousBlock_Call {
	return &StorageBlockInterface_GetPreviousBlock_Call{Call: _e.mock.On("GetPreviousBlock", ctx, offset, dbTx)}
}

func (_c *StorageBlockInterface_GetPreviousBlock_Call) Run(run func(ctx context.Context, offset uint64, dbTx pgx.Tx)) *StorageBlockInterface_GetPreviousBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageBlockInterface_GetPreviousBlock_Call) Return(_a0 *pgstorage.L1Block, _a1 error) *StorageBlockInterface_GetPreviousBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageBlockInterface_GetPreviousBlock_Call) RunAndReturn(run func(context.Context, uint64, pgx.Tx) (*pgstorage.L1Block, error)) *StorageBlockInterface_GetPreviousBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageBlockInterface creates a new instance of StorageBlockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageBlockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageBlockInterface {
	mock := &StorageBlockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
