// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import mock "github.com/stretchr/testify/mock"

// StorageTransactionInterface is an autogenerated mock type for the StorageTransactionInterface type
type StorageTransactionInterface struct {
	mock.Mock
}

type StorageTransactionInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageTransactionInterface) EXPECT() *StorageTransactionInterface_Expecter {
	return &StorageTransactionInterface_Expecter{mock: &_m.Mock}
}

// NewStorageTransactionInterface creates a new instance of StorageTransactionInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageTransactionInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageTransactionInterface {
	mock := &StorageTransactionInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
