// Code generated by mockery. DO NOT EDIT.

package mock_synchronizer

import mock "github.com/stretchr/testify/mock"

// SynchornizerStatusQuerier is an autogenerated mock type for the SynchornizerStatusQuerier type
type SynchornizerStatusQuerier struct {
	mock.Mock
}

type SynchornizerStatusQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *SynchornizerStatusQuerier) EXPECT() *SynchornizerStatusQuerier_Expecter {
	return &SynchornizerStatusQuerier_Expecter{mock: &_m.Mock}
}

// IsSynced provides a mock function with given fields:
func (_m *SynchornizerStatusQuerier) IsSynced() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSynced")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SynchornizerStatusQuerier_IsSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSynced'
type SynchornizerStatusQuerier_IsSynced_Call struct {
	*mock.Call
}

// IsSynced is a helper method to define mock.On call
func (_e *SynchornizerStatusQuerier_Expecter) IsSynced() *SynchornizerStatusQuerier_IsSynced_Call {
	return &SynchornizerStatusQuerier_IsSynced_Call{Call: _e.mock.On("IsSynced")}
}

func (_c *SynchornizerStatusQuerier_IsSynced_Call) Run(run func()) *SynchornizerStatusQuerier_IsSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SynchornizerStatusQuerier_IsSynced_Call) Return(_a0 bool) *SynchornizerStatusQuerier_IsSynced_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SynchornizerStatusQuerier_IsSynced_Call) RunAndReturn(run func() bool) *SynchornizerStatusQuerier_IsSynced_Call {
	_c.Call.Return(run)
	return _c
}

// NewSynchornizerStatusQuerier creates a new instance of SynchornizerStatusQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSynchornizerStatusQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *SynchornizerStatusQuerier {
	mock := &SynchornizerStatusQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
