// Code generated by mockery. DO NOT EDIT.

package mock_state

import (
	context "context"

	entities "github.com/0xPolygonHermez/zkevm-synchronizer-l1/state/entities"
	mock "github.com/stretchr/testify/mock"
)

// StateKVInterface is an autogenerated mock type for the StateKVInterface type
type StateKVInterface struct {
	mock.Mock
}

type StateKVInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StateKVInterface) EXPECT() *StateKVInterface_Expecter {
	return &StateKVInterface_Expecter{mock: &_m.Mock}
}

// GetKV provides a mock function with given fields: ctx, key, value, dbTx
func (_m *StateKVInterface) GetKV(ctx context.Context, key string, value interface{}, dbTx entities.Tx) error {
	ret := _m.Called(ctx, key, value, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetKV")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, entities.Tx) error); ok {
		r0 = rf(ctx, key, value, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateKVInterface_GetKV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKV'
type StateKVInterface_GetKV_Call struct {
	*mock.Call
}

// GetKV is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - dbTx entities.Tx
func (_e *StateKVInterface_Expecter) GetKV(ctx interface{}, key interface{}, value interface{}, dbTx interface{}) *StateKVInterface_GetKV_Call {
	return &StateKVInterface_GetKV_Call{Call: _e.mock.On("GetKV", ctx, key, value, dbTx)}
}

func (_c *StateKVInterface_GetKV_Call) Run(run func(ctx context.Context, key string, value interface{}, dbTx entities.Tx)) *StateKVInterface_GetKV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(entities.Tx))
	})
	return _c
}

func (_c *StateKVInterface_GetKV_Call) Return(_a0 error) *StateKVInterface_GetKV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateKVInterface_GetKV_Call) RunAndReturn(run func(context.Context, string, interface{}, entities.Tx) error) *StateKVInterface_GetKV_Call {
	_c.Call.Return(run)
	return _c
}

// SetKV provides a mock function with given fields: ctx, key, value, dbTx
func (_m *StateKVInterface) SetKV(ctx context.Context, key string, value interface{}, dbTx entities.Tx) error {
	ret := _m.Called(ctx, key, value, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for SetKV")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, entities.Tx) error); ok {
		r0 = rf(ctx, key, value, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateKVInterface_SetKV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKV'
type StateKVInterface_SetKV_Call struct {
	*mock.Call
}

// SetKV is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - dbTx entities.Tx
func (_e *StateKVInterface_Expecter) SetKV(ctx interface{}, key interface{}, value interface{}, dbTx interface{}) *StateKVInterface_SetKV_Call {
	return &StateKVInterface_SetKV_Call{Call: _e.mock.On("SetKV", ctx, key, value, dbTx)}
}

func (_c *StateKVInterface_SetKV_Call) Run(run func(ctx context.Context, key string, value interface{}, dbTx entities.Tx)) *StateKVInterface_SetKV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(entities.Tx))
	})
	return _c
}

func (_c *StateKVInterface_SetKV_Call) Return(_a0 error) *StateKVInterface_SetKV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateKVInterface_SetKV_Call) RunAndReturn(run func(context.Context, string, interface{}, entities.Tx) error) *StateKVInterface_SetKV_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateKVInterface creates a new instance of StateKVInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateKVInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateKVInterface {
	mock := &StateKVInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
