// Code generated by mockery. DO NOT EDIT.

package mock_storage

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// execQuerier is an autogenerated mock type for the execQuerier type
type execQuerier struct {
	mock.Mock
}

type execQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *execQuerier) EXPECT() *execQuerier_Expecter {
	return &execQuerier_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, _a1, arguments
func (_m *execQuerier) ExecContext(ctx context.Context, _a1 string, arguments ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, arguments...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return rf(ctx, _a1, arguments...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, _a1, arguments...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, _a1, arguments...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// execQuerier_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type execQuerier_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - arguments ...interface{}
func (_e *execQuerier_Expecter) ExecContext(ctx interface{}, _a1 interface{}, arguments ...interface{}) *execQuerier_ExecContext_Call {
	return &execQuerier_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, _a1}, arguments...)...)}
}

func (_c *execQuerier_ExecContext_Call) Run(run func(ctx context.Context, _a1 string, arguments ...interface{})) *execQuerier_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *execQuerier_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *execQuerier_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *execQuerier_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (sql.Result, error)) *execQuerier_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, _a1, args
func (_m *execQuerier) QueryContext(ctx context.Context, _a1 string, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (*sql.Rows, error)); ok {
		return rf(ctx, _a1, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Rows); ok {
		r0 = rf(ctx, _a1, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, _a1, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// execQuerier_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type execQuerier_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - args ...interface{}
func (_e *execQuerier_Expecter) QueryContext(ctx interface{}, _a1 interface{}, args ...interface{}) *execQuerier_QueryContext_Call {
	return &execQuerier_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, _a1}, args...)...)}
}

func (_c *execQuerier_QueryContext_Call) Run(run func(ctx context.Context, _a1 string, args ...interface{})) *execQuerier_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *execQuerier_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *execQuerier_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *execQuerier_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (*sql.Rows, error)) *execQuerier_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, _a1, args
func (_m *execQuerier) QueryRowContext(ctx context.Context, _a1 string, args ...interface{}) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Row); ok {
		r0 = rf(ctx, _a1, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// execQuerier_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type execQuerier_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - args ...interface{}
func (_e *execQuerier_Expecter) QueryRowContext(ctx interface{}, _a1 interface{}, args ...interface{}) *execQuerier_QueryRowContext_Call {
	return &execQuerier_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, _a1}, args...)...)}
}

func (_c *execQuerier_QueryRowContext_Call) Run(run func(ctx context.Context, _a1 string, args ...interface{})) *execQuerier_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *execQuerier_QueryRowContext_Call) Return(_a0 *sql.Row) *execQuerier_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *execQuerier_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) *sql.Row) *execQuerier_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// newExecQuerier creates a new instance of execQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newExecQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *execQuerier {
	mock := &execQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
