name: Check Version
on:
  push:
    branches:
      - 'release/**'
      - 'feature/**'
      - 'fix/**'
      - '**'
  pull_request:

jobs:
    check_version:
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.21.x
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Check Version
              run: make check-is-new-version