# placeholder for e2e tests
name: Test e2e
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}


jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.21.x ]
        goarch: [ "amd64" ]
        e2e-group: [ "rollup" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4



    
